app/about-us/certification/page.tsx
components/atoms/portable-text.tsx
package-lock.json
package.json
types/certification-type.ts

- Created a responsive certification page to enhance user experience across devices.
- Successfully displayed certification data integrated with Sanity.

feat(PW-93): responsive certification page

---

sanity/schemaTypes/index.ts
sanity/schemaTypes/product.ts
sanity/services/product-query.ts
types/product-type.ts

- Created a schema for the Certification CMS.
- Integrated a query for certification data.
- Created new type for product data inside `types` folder.

feat(PW-107): cms our-product

---

sanity/schemaTypes/arthawena-at-glance.ts
sanity/schemaTypes/index.ts
sanity/services/arthawena-at-glance-query.ts
types/arthawena-at-glance-type.ts

- Created a schema for the arthawena-at-glance CMS.
- Integrated a query for arthawena-at-glance data.
- Created new type for arthawena-at-glance data inside types folder.

feat(PW-105): cms arthawena at glance

---

sanity/schemaTypes/index.ts
sanity/schemaTypes/technology.ts
sanity/services/technology-query.ts
types/technology-type.ts

- Created a schema for the Our Technology CMS.
- Integrated a query for Our Technology data.
- Created new type for Our Technology data inside types folder.

feat(PW-108): cms our-technology

---

types/technology-type.ts

- Added images field to TechnologyType for handling image array.

fix(PW-108): technology-type updated

---

app/globals.css
app/our-business/technology/page.tsx
components/atoms/swiper-navigation.tsx

- Created a responsive Technology page to enhance user experience across devices.
- Successfully displayed Technology data integrated with Sanity.
- Created and integrated custom swiper-navigation into swiper component on large devices.

feat(PW-95): responsive technology page

---

app/our-business/our-product/page.tsx

- Created a responsive our-product page to enhance user experience across devices.
- Seamlessly displayed our-product data integrated with Sanity.

feat(PW-94): responsive our-product page

---

app/about-us/arthawena-at-glance/page.tsx

- Applied style standardization.
- Handle optional employee and location fields.

style: style standardization

---

components/atoms/portable-text.tsx

> [!NOTE]
> The refactoring aims to reduce complexity and the functionality stays as is.
| Before ❌ 🤮 | After ✅ 😎 |
|--------|--------|
| <img width="488" alt="SCR-20240920-igju" src="https://github.com/user-attachments/assets/caa9932d-0110-46bf-9091-189d903bef86"> | <img width="636" alt="SCR-20240920-irpz" src="https://github.com/user-attachments/assets/fa99554f-9174-43e7-8d8f-5d30d72d1d8a"> | 
✅ Tested

refactor: portable text component refactored

---

app/sustainability/arthawena-for-sustainability/page.tsx

Adjustment circle item on hero section

fix: hero section

---

app/contact/page.tsx

- remove unnecessary `<p>` elements
- refactor styling under contact section
- fix unaligned contacts when the screen is being shrank

fix(PW-113):remove unnecessary <p> elements and refactor styling

---

app/sustainability/csr-programs/page.tsx

- Applied style standardization.
- Optimized images size in Sanity.

style: applied style standardization

---

app/contact/page.tsx
tailwind.config.ts

- Applied style standardization.
- Added hover effect on submit button of the desktop version.

style(PW-100): applied style standardization

---

app/careers/culture/page.tsx

- Applied style standardization.
- Fixed items alignments.

style(PW-101): applied style standardization

---

components/atoms/video-player.tsx
components/molecules/haro-carousel.tsx

- Updated video thumbnail to start at the 9th second.
- Added functionality to reset video playback to the start (1 second) when played manually.
- Implemented logic to automatically move to the next slide 3 seconds after the video is manually paused.

fix: video controls enhancement

---

sanity.config.ts
sanity/schemaTypes/arthawena-at-glance.ts
sanity/schemaTypes/certification.ts
sanity/schemaTypes/product.ts
sanity/schemaTypes/technology.ts

- fix collection name
- use position validation utils
- remove `goals` collection restriction on adding document

fix: sanity collection name and use position utils

---

app/sustainability/csr-programs/page.tsx

- Enhanced map image resolution.
- Adjusted legend positioning on small devices.
- Corrected inaccurate text.
- Adjusted CSR data layout for 2xL devices.

fix(PW-99): layouting and text correction

---

app/page.tsx

- Change text from "Who we are" to "Who Are We"
- Apply styling "tracking-wider" to the text of "THE MOST RELIABLE TIN CAN SUPPLIER IN INDONESIA"

Designer Feedback - Home

---

sanity/schemaTypes/banner.ts
sanity/services/banner-query.ts

- Added new field to support video thumbnail.

feat: added video thumbnail field on Sanity

---

components/molecules/navbar.tsx

**Client Feedback Point 1**
> [!WARNING]
> Please don't merge this branch into main.

style: enlarged navbar company logo

---

app/page.tsx

**Client Feedback Point 2**
> [!WARNING]
> Please don't merge this branch into main.

style: adjusted company values layout

---

app/careers/culture/page.tsx

Changing layout of Culture page (Desktop version)
- Text: Culture and We prioritize... moved to the center
- Image: Text is now above the image, no more cropped image.

Style(PW-115):customer feedback Culture page

---

components/atoms/video-player.tsx

- Added Framer Motion variants for video player animation on small devices.
- Applied the animation only when the screen width is less than 1024.

feat: created video-player animation for small devices

---

components/molecules/footer.tsx
components/molecules/haro-carousel.tsx

- updated footer links.
- updated paused video duration to 6000ms.

style: updated footer links and paused video duration
